#!/bin/sh
#
# Copyright (C) 2013-2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

ANACRON_CONFIG="/etc/anacrontab"
ANACRON_SCRIPT_DIR="/var/lib/anacron/"

# Create anacron config file
cat <<EOF > ${ANACRON_CONFIG}
# /etc/anacrontab: configuration file for anacron

# See anacron(8) and anacrontab(5) for details.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# These replace cron's entries
1       5       cron.daily       nice run-parts --report /etc/cron.daily
7       10      cron.weekly      nice run-parts --report /etc/cron.weekly
@monthly        15      cron.monthly nice run-parts --report /etc/cron.monthly

# added by plugin
EOF

# Add anacron tasks
# format:
#   period        delay  job-identifier  command
#   @period_name  delay  job-identifier  command

count=$(omv_config_get_count "//services/anacron/task")
index=1
while [ ${index} -le ${count} ]; do

    enable=$(omv_config_get "//services/anacron/task[position()=${index}]/enable")
    
    if [ 1 = ${enable} ]; then
        period=$(omv_config_get "//services/anacron/task[position()=${index}]/period")
        delay=$(omv_config_get "//services/anacron/task[position()=${index}]/delay")
        identifier=$(omv_config_get "//services/anacron/task[position()=${index}]/identifier")
        username=$(omv_config_get "//services/anacron/task[position()=${index}]/username")
        command=$(omv_config_get "//services/anacron/task[position()=${index}]/command")
        comment=$(omv_config_get "//services/anacron/task[position()=${index}]/comment")

        if [ `$(omv_config_get "//services/anacron/task[position()=${index}]/sendemail")` = "1" ]; then
            command2="${command} \| mail -s \"Anacron - ${comment}\" -a \"From: Anacron Daemon <${username}>\" ${username} >/dev/null 2>&1"
        else
            command2="${command}"
        fi

        echo "${period}\t${delay}\t${identifier}\t${command2}" >> ${ANACRON_CONFIG}
    fi

    index=$(( ${index} + 1 ))
done
