#!/bin/bash
#
# Copyright (C) 2013-2017 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

ANACRON_CONFIG="/etc/anacrontab"
ANACRON_SCRIPT_DIR="/var/lib/anacron/"
ANACRON_SECTIONNAME="omvanacron"

if [ ! -d "${ANACRON_SCRIPT_DIR}" ]; then
    mkdir -p ${ANACRON_SCRIPT_DIR}
    chmod 0755 ${ANACRON_SCRIPT_DIR}
fi

# Add anacron tasks
# format:
#   period        delay  job-identifier  command
#   @period_name  delay  job-identifier  command

anacronent=$(

echo -n "# >>> [${ANACRON_SECTIONNAME}]\n";

count=$(omv_config_get_count "//services/anacron/task")
index=1
while [ ${index} -le ${count} ]; do

    enable=$(omv_config_get "//services/anacron/task[position()=${index}]/enable")

    if [ 1 = ${enable} ]; then
        period=$(omv_config_get "//services/anacron/task[position()=${index}]/period")
        delay=$(omv_config_get "//services/anacron/task[position()=${index}]/delay")
        identifier=$(omv_config_get "//services/anacron/task[position()=${index}]/identifier")
        username=$(omv_config_get "//services/anacron/task[position()=${index}]/username")
        command=$(omv_config_get "//services/anacron/task[position()=${index}]/command")
        comment=$(omv_config_get "//services/anacron/task[position()=${index}]/comment")
        sendemail=$(omv_config_get "//services/anacron/task[position()=${index}]/sendemail")
        
        if [ "${sendemail}" = "1" ]; then
            command2="${command} \| mail -s \"Anacron - ${comment}\" -a \"From: Anacron Daemon <${username}>\" ${username} >/dev/null 2>&1"
        else
            command2="${command}"
        fi

        echo -n "${period}\t${delay}\t${identifier}\t${command2}\n"
    fi

    index=$(( ${index} + 1 ))
done

echo -n "# <<< [${ANACRON_SECTIONNAME}]")

# Append anacron entries if not still present or replace existing entries.
if ! grep -E "^# >>> \[${ANACRON_SECTIONNAME}\]\s*$" ${ANACRON_CONFIG} >/dev/null; then
    echo -e "${anacronent}" >> ${ANACRON_CONFIG}
else
    sed -i "/# >>> \[${ANACRON_SECTIONNAME}\]/,/# <<< \[${ANACRON_SECTIONNAME}\]/ c ${anacronent}" ${ANACRON_CONFIG}
fi
