#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

ANACRON_SCRIPT_DIR="/var/lib/anacron"

case "$1" in
    purge)
        rm -rf /var/lib/anacron

        # remove openmediavault-anacron lines from /etc/anacrontab

    ;;

    remove)
        # remove openmediavault-anacron lines from /etc/anacrontab
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
