#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

ANACRON_SCRIPT_DIR="/var/lib/anacron"

case "$1" in
    configure)
        # Activate package triggers.
        dpkg-trigger update-workbench

        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.anacron"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.anacron" "${2}"
        fi

        omv-salt deploy run anacron || :
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
