#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

ANACRON_SCRIPT_DIR="/var/lib/anacron"

case "$1" in
    configure)

    if ! omv_config_exists "/config/services/anacron"; then
        echo "Initial configuration."
        omv_config_add_element "/config/services" "anacron" "${object}" true
    fi

    if [ ! -d "${ANACRON_SCRIPT_DIR}" ]; then
        mkdir -p ${ANACRON_SCRIPT_DIR}
        chmod 0755 ${ANACRON_SCRIPT_DIR}
    fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
