#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

ANACRON_SCRIPT_DIR="/var/lib/anacron"
ANACRON_CONFIG="/etc/anacrontab"
ANACRON_SECTIONNAME="omvanacron"

case "$1" in
    purge)
        rm -rf /var/lib/anacron
    ;;

    remove)
        sed -i "/# >>> \[${ANACRON_SECTIONNAME}\]/,/# <<< \[${ANACRON_SECTIONNAME}\]/d" ${ANACRON_CONFIG}
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
